[tableau]
token_name = "streamlit-app"
token_secret = "26BIukz3SS666t2yvI330Q==:5USgctEpmiErG2wBhqYd6Nbwx3pCUzy6"
server_url = "https://abc01.online.tableau.com/"
site_id = "streamlitexample"  # in your site's URL behind the server_url
